# Download TA-Lib from https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib
# pip install C:\Users\jonat\PycharmProjects\Trading-ML\DL\TA-lib\TA_Lib-0.4.24-cp39-cp39-win_amd64.whl

API_KEY = '<API_KEY>'
SECRET_KEY = '<SECRET_KEY>'
API_BASE_URL = 'https://paper-api.alpaca.markets'
TICKERS = ['BTCUSD']
EXCHANGES = ['CBSE']
TIMEFRAME_DL = '5Min'
TFRAMES = ['5Min', '30Min', '1H', '4H']
df_list = []
dl_path = r'.\DL\DL_files'
transform_path = r'.\DL\transform_files'
from_year = 2021
from_month = 12
from_day = 1


# DL configurations
BC_charts_list = ['market-price',
                  'market-cap',
                  'trade-volume',
                  'avg-block-size',
                  'n-transactions-per-block',
                  'median-confirmation-time',
                  'avg-confirmation-time',
                  'hash-rate',
                  'difficulty',
                  'miners-revenue',
                  'transaction-fees-usd',
                  'cost-per-transaction',
                  'n-unique-addresses',
                  'n-transactions',
                  'transactions-per-second',
                  'output-volume',
                  'mempool-count',
                  'mempool-growth',
                  'mempool-size',
                  'utxo-count']

crypto_influencers = ['RagingVentures',
                      'rsandler21969',
                      'ThomasUBarton1',
                      'AltaFoxCapital',
                      'HaydenCapital',
                      'GavinSBaker',
                      '1MainCapital',
                      'alluvialcapital',
                      'JohnHuber72',
                      'TidefallCapital',
                      'John_Hempton',
                      'LuisVSanchez777',
                      'realdennishong',
                      'DanielSLoeb1',
                      'plaffont',
                      'B3_MillerValue',
                      'BillAckman',
                      'davidein',
                      'SuperMugatu ',
                      'AndurandPierre',
                      'jessecohn4',
                      'cablecarcapital',
                      'CliffordSosin',
                      'StevenACohen2',
                      'joelmcohen',
                      'Post_Market',
                      'breadcrumbsre',
                      'BigRiverCapita1',
                      'AlderLaneeggs',
                      'WallStCynic',
                      'ActAccordingly',
                      'DonutShorts',
                      'unemon1',
                      'BorrowCost',
                      'NonGaap',
                      'JBierne',
                      'Fritz844',
                      'FoxCastlehold',
                      'JerryCap ',
                      'MoatsLikeKodak',
                      'marginalidea',
                      'ValueSituations',
                      'AndrewRangeley',
                      'TSOH_Investing',
                      'ClarityToast',
                      'Valuedontlie',
                      'clueless_1337',
                      'hhhypergrowth',
                      'footnoted',
                      'TimyanBankAlert',
                      'WaltHudson',
                      'irbezek',
                      'compound248',
                      'GrapefruitGals',
                      'richard_chu97',
                      'FoolAllTheTime',
                      'dylan522p',
                      'VetTechTrader',
                      'dirtcheapstocks',
                      'iancassel',
                      'schaudenfraud',
                      '10kdiver',
                      'LSValue',
                      'cpg_girl',
                      'RihardJarc',
                      'SleepwellCap',
                      'bluff_capital',
                      'borrowed_ideas',
                      'buysidebio',
                      'InvestmentTalkk',
                      'Alex__Pitti',
                      'WallStCritic',
                      'CasinoCapital',
                      'TheIpHawk',
                      'LukeWolgram',
                      'juliaskripkaser',
                      'ShortSightedCap',
                      'bizalmanac',
                      'YHamiltonBlog',
                      'BillBrewsterSCG',
                      'talbottzink',
                      'sharesleuth',
                      'caveatemptorst1',
                      'QuisitiveInvest',
                      'YellowLabLife',
                      'TurnerNovak',
                      'awilkinson',
                      'realEstateTrent',
                      'Crussian17',
                      'Plum_Capital',
                      'moon_shine15',
                      'TESLAcharts',
                      'MadThunderdome',
                      'Amarillo_Slim1',
                      'NewmoonCap',
                      'special_sits',
                      'NeckarValue',
                      'pmje73',
                      'PythiaR',
                      'MarcusFrampton',
                      'MattPaulsonSD',
                      'bespokeinvest',
                      'WallStreetOasis',
                      'SJosephBurns',
                      'yourmoneygeek',
                      'IBDinvestors',
                      'irusha',
                      'Stocktwits',
                      'hmeisler',
                      'DKellerCMT',
                      'DocumentingBTC',
                      'WClementeIII',
                      'nic__carter',
                      'Gladstein',
                      'BTC_Archive',
                      'APompliano',
                      '100trillionUSD',
                      'MessariCrypto',
                      'MartyBent',
                      'aantonop']

financial_news = ['business',
                  'markets',
                  'crypto',
                  'SeekingAlpha',
                  'CNNMoneyInvest',
                  'CNBCnow',
                  'Forbes',
                  'ForbesCrypto',
                  'MarketWatch',
                  'WSJ',
                  'IBTimes',
                  'TheEconomist',
                  'FinancialTimes',
                  'Nasdaq',
                  'ReutersBiz',
                  'TheStreet',
                  'YahooFinance']

general_news = ['mashable',
                'cnnbrk',
                'big_picture',
                'theonion',
                'time',
                'breakingnews',
                'bbcbreaking',
                'espn',
                'harvardbiz',
                'gizmodo',
                'techcrunch',
                'wired',
                'wsj',
                'smashingmag',
                'pitchforkmedia',
                'rollingstone',
                'whitehouse',
                'cnn',
                'tweetmeme',
                'peoplemag',
                'natgeosociety',
                'nytimes',
                'lifehacker',
                'foxnews',
                'waitwait',
                'newsweek',
                'huffingtonpost',
                'newscientist',
                'mental_floss',
                'theeconomist',
                'emarketer',
                'engadget',
                'cracked',
                'slate',
                'bbcclick',
                'fastcompany',
                'reuters',
                'incmagazine',
                'eonline',
                'rww',
                'gdgt',
                'instyle',
                'mckquarterly',
                'enews',
                'nprnews',
                'usatoday',
                'mtv',
                'freakonomics',
                'boingboing',
                'billboarddotcom',
                'empiremagazine',
                'todayshow',
                'good',
                'gawker',
                'msnbc_breaking',
                'cbsnews',
                'guardiantech',
                'usweekly',
                'life',
                'sciam',
                'pastemagazine',
                'drudge_report',
                'parisreview',
                'latimes',
                'telegraphnews',
                'abc7',
                'arstechnica',
                'cnnmoney',
                'nprpolitics',
                'nytimesphoto',
                'nybooks',
                'nielsenwire',
                'io9',
                'sciencechannel',
                'usabreakingnews',
                'vanityfairmag',
                'cw_network',
                'bbcworld',
                'abc',
                'themoment',
                'socialmedia2day',
                'slashdot',
                'washingtonpost',
                'tpmmedia',
                'msnbc',
                'wnycradiolab',
                'cnnlive',
                'davos',
                'planetmoney',
                'cnetnews',
                'politico',
                'tvnewser',
                'guardiannews',
                'yahoonews',
                'seedmag',
                'tvguide',
                'travlandleisure',
                'newyorkpost',
                'discovermag',
                'sciencenewsorg']

usernames_dict = {'crypto_influencers': crypto_influencers,
                  'financial_news': financial_news,
                  'general_news': general_news}

keyword_dict = {'BTCUSD': 'Bitcoin',
                'ETHUSD': 'Ethereum'}
